trigger:
- dev

pr:
- dev

pool:
  name: 'SelfHostedPool'

steps:
- powershell: |
    Write-Host "Java version:"
    java -version
    Write-Host "Compiling Java source files..."

    $files = Get-ChildItem -Recurse -Filter *.java phase-0-algorithms
    javac $files
  displayName: 'Compile Java (Phase 0)'
'
